### ISSUE TITLE
[[Issue(?)]] Possible Need to Update README?

### ISSUE THREAD

**Issue by WammKD** [diaspora/diaspora_federation#105]
Granted, I haven't used Rails in, like, 3–4 years and was planning on refreshing myself before diving into working with this (so I may be missing something obvious that someone more familiar with Rails would immediately pick up on) but thought, having install Rails, I could first just follow the initial instructions on the README to just get a base setup.

So I'm running Ruby version 2.5.1p57 and Rails version 2.5.1.

I ran `rails new myapp`, `cd`ed into the directory, added "gem 'diaspora_federation-rails'" to my Gemfile, and ran `bundle install`.

That seemed to install just fine so I then added `mount DiasporaFederation::Engine => "/"` to "config/routes.rb" and the thing mentioned to add to "config/initializers/diaspora_federation.rb".

I then tried running `rails server` to see if things would run and got

> => Booting Puma
> => Rails 5.2.1 application starting in development 
> => Run `rails server -h` for more startup options
> Exiting
> Traceback (most recent call last):
> 	82: from bin/rails:3:in `<main>'
> 	81: from bin/rails:3:in `load'
> 	80: from /tmp/myapp/bin/spring:15:in `<top (required)>'
> 	79: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
> 	78: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
> 	77: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
> 	76: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
> 	75: from /var/lib/gems/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
> 	74: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
> 	73: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
> 	72: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
> 	71: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
> 	70: from /tmp/myapp/bin/rails:9:in `<top (required)>'
> 	69: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
> 	68: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
> 	67: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
> 	66: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
> 	65: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
> 	64: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
> 	63: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
> 	62: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
> 	61: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
> 	60: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
> 	59: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
> 	58: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
> 	57: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
> 	56: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
> 	55: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:51:in `start'
> 	54: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
> 	53: from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
> 	52: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:27:in `app'
> 	51: from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
> 	50: from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
> 	49: from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
> 	48: from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
> 	47: from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
> 	46: from config.ru:in `<main>'
> 	45: from config.ru:in `new'
> 	44: from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
> 	43: from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
> 	42: from config.ru:3:in `block in <main>'
> 	41: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
> 	40: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
> 	39: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
> 	38: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
> 	37: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
> 	36: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
> 	35: from /tmp/myapp/config/environment.rb:5:in `<main>'
> 	34: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
> 	33: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
> 	32: from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
> 	31: from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
> 	30: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
> 	29: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
> 	28: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
> 	27: from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
> 	26: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
> 	25: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
> 	24: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
> 	23: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `each'
> 	22: from /usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
> 	21: from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
> 	20: from /usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
> 	19: from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
> 	18: from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
> 	17: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
> 	16: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
> 	15: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
> 	14: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
> 	13: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:613:in `each'
> 	12: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
> 	11: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
> 	10: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
> 	 9: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
> 	 8: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
> 	 7: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
> 	 6: from /tmp/myapp/config/initializers/diaspora_federation.rb:1:in `<main>'
> 	 5: from /var/lib/gems/2.5.0/gems/diaspora_federation-0.2.4/lib/diaspora_federation.rb:140:in `configure'
> 	 4: from /tmp/myapp/config/initializers/diaspora_federation.rb:3:in `block in <main>'
> 	 3: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
> 	 2: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
> 	 1: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
> /var/lib/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant': uninitialized constant AppConfig (NameError)

Like I said, I might just be missing something that would be obvious to anyone familiar with Rails but I don't know for sure (obviously). I figure, if it isn't, I might as well raise the issue here in case it's something that should just be tweaked (and doesn't require more extensive setup) and would be worth updating the README for future developers.

Also, would definitely be curious as to why things aren't working, for my own knowledge. Thanks for any help!

**Comment by SuperTux88** [comment]
The `config/initializers/diaspora_federation.rb` in the README is only an incomplete example (based on how we use it in diaspora), you need to configure it with your own values. For example in diaspora we have the `server_uri` in `AppConfig.pod_uri`, if your app doesn't have that (which is very likely), then you need to set it with your own values, for example for development on localhost:

```ruby
config.server_uri = "http://localhost:3000"
```

Or use a variable if you have the domain somewhere in your app.

Also you need to set all other settings and callbacks in the config the way you need it. You can find all settings [here in the documentation](https://www.rubydoc.info/gems/diaspora_federation/DiasporaFederation#class_attr_details) and callback are listed [here](https://www.rubydoc.info/gems/diaspora_federation/DiasporaFederation#define_callbacks-class_method).

**Comment by WammKD** [comment]
Gotcha; it might be useful adding a link or something to the details of what needs to be set or how to set those things? The first link you provide isn't overly obvious that it's settings and more looks like just functions you can call (let alone how I would set them, though that may, again, go back to me needing to refresh on how to use Rails).

In any case, thanks for the quick reply and clarification! Definitely super appreciated.

**Comment by SuperTux88** [comment]
I improved the README a bit with your feedback to hopefully make it clearer, let me know if that's clear enough now.

**Comment by WammKD** [comment]
Oooh, yeah; that definitely makes it more clear what that code snippet is doing. Leastwise, it makes a lot more sense to my brain that things are being set and what kind of things could be set. It definitely feels a _lot_ more helpful, to me. Looks great!

**Comment by SuperTux88** [comment]
Thanks for your feedback :)

**Comment by WammKD** [comment]
No problem! One last note, since it's now in the README –  I put it together from https://www.rubydoc.info/gems/diaspora_federation/DiasporaFederation#configure-class_method (yay good documentation!) but the `server_uri` needs to be wrapped in a `URI` (e.g. `URI("http://localhost:3000")`) for it to be accepted as valid; might confound newbies (myself included), otherwise, when they try running `rails server`.

**Comment by SuperTux88** [comment]
Thanks, I should probably read the documentation myself first :D fixed it.
