### ISSUE TITLE
Please release version with Rails 6 support

### ISSUE THREAD

**Issue by dleidert** [diaspora/diaspora_federation#120]
Hi, would you mind doing an official release with Rails 6 support? It seems this support is in the master branch, but has not been released with version 0.2.7.

**Comment by SuperTux88** [comment]
I will release 0.3.0 soon, but there are still a few things missing.

**Comment by SuperTux88** [comment]
Sorry it took a bit longer, but 0.3.0 with Rails 6 support is now released.
