### ISSUE TITLE
Entity-XML (Salmon-Payload) refactoring

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora_federation#28]
The XML (the salmon-payload) is currently wrapped like this:

``` xml
<XML>
  <post>
    {data}
  </post>
</XML>
```

`{data}` is the entity as xml.

This additional wrapping is there for historic reasons and can be removed...
### v0.1.0 (for diaspora 0.6.0.0)
- [x] allow receive unwrapped entities
- [x] still send and receive wrapped entities
### v0.2.0 (for diaspora 0.7.0.0)
- [x] receive wrapped and unwrapped entities
- [x] send unwrapped entities
### v0.3.0 (probably for diaspora 0.8.0.0)
- [ ] remove old unwrap-code

**Comment by cmrd-senya** [comment]
I've introduced [changes](https://wiki.diasporafoundation.org/index.php?title=Federation_protocol_overview&diff=4715&oldid=4462) to the [protocol overview page](https://wiki.diasporafoundation.org/Federation_protocol_overview) according to this PR.
