### ISSUE TITLE
Salmon Refactoring

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora_federation#30]
We use currently a `<diaspora>` XML wrapper for the salmon magic envelope. The main reason for this wrapper is to send an `author_id` in the header. But we can use the `key_id` from the magic envelope for that. The second reason is for the aes-crypt for private-messages. But because we encrypt the magic envelope payload and the header separately, we need two aes keys.
## public messages

For public messages we can simply use the normal magic envelope as specified here: https://cdn.rawgit.com/salmon-protocol/salmon-protocol/master/draft-panzer-magicsig-01.html
- Add `key_id` with the base64url encoded diaspora-id (see 3.1)
- No additional wrapping with own xml, no diaspora-header.
- send it with `Content-Type: application/magic-envelope+xml` as request-body (no `xml=` param) (see [salmon](https://cdn.rawgit.com/salmon-protocol/salmon-protocol/master/draft-panzer-salmon-00.html#RPF))
- the data-payload of the magic-env would stay the same (changes from #28 + #29)

This is much simpler and it is basically the salmon/magic-env spec.
## private messages

For private messages we need an encryption again. But instead of using the complicated "EncryptedSlap" with separately encrypted header and magic-env payload (another hack in the magic-env to encrypt/decrypt the data-payload). we can simply encrypt the whole magic-env (so the magic-env can be handled exactly the same as for public-messages, no additional hacks needed). For the crypt-wrapper I used a similar json-structure as for the encrypted_header from the "EncryptedSlap":

```
{
  "aes_key": "...",
  "encrypted_magic_envelope": "..."
}
```

The `aes_key` is the same as for the `encrypted_header`: It contains the base64 encoded AES `key` and `iv` as json, encrypted with the recipients public key and base64 encoded again:

```
{
  "key": "...",
  "iv": "..."
}
```

The `encrypted_magic_envelope` is the magic-env encrypted with the `aes_key` and base64 encoded. After decoding and decrypting it can be parsed like a normal magic envelope(see public messages). It also contains the `key_id`.

This crypt-json should be transmitted also directly in the request-body as `Content-Type: application/json`.

Because the new messages don't use the old unnecessary `xml=` parameter, we can decide with the content-type and the param, if we received a new or an old message for the transition period.
### v0.1.0 (for diaspora 0.6.0.0)
- [x] send the old Slap and EncryptedSlap (`<diaspora>...</diaspora>`)
- [x] send the `key_id` in the magic envelope
- [x] use the `author_id` or the `key_id` to verify the signature of the magic envelope 
- [x] can receive and parse old Slap and EncryptedSlap (`<diaspora>...</diaspora>`)
- [x] can receive and parse a raw magic envelope without wrapper
- [x] can receive and parse a encrypted magic envelope with crypt-json wrapper
### v0.2.0 (for diaspora 0.7.0.0)
- [x] send the new raw magic envelope and encrypted magic envelope with crypt-json-wrapper
- [x] send the `key_id` in the magic envelope
- [x] use the `author_id` or the `key_id` to verify the signature of the magic envelope 
- [x] can receive and parse old Slap and EncryptedSlap (`<diaspora>...</diaspora>`)
- [x] can receive and parse a raw magic envelope and encrypted magic envelope with crypt-json wrapper
### v0.3.0 (probably for diaspora 0.8.0.0)
- [ ] remove old Slap and EncryptedSlap support and cleanup.

**Comment by cmrd-senya** [comment]
> The main reason for this wrapper is to send an **author_id** in the header.

**Comment by SuperTux88** [comment]
Thanks, fixed.

**Comment by cmrd-senya** [comment]
Do we really need to encode the ```key_id``` with base64? Will it ever contain anything but latin characters and "@"?

**Comment by SuperTux88** [comment]
the base64 encoding is from the salmon spec: "The format of this parameter is unspecified except that all characters must be from the base64url allowed character set."

**Comment by cmrd-senya** [comment]
> Note that the last step in the preparation of the payload message was to base64-encode it. That string must be base64-encoded again to form the <me:data> element. However, this time, it must be encoded with the slightly-different base64url encoding. So your payload message will end up double-wrapped in base64-encoding. -- *[source](https://wiki.diasporafoundation.org/Federation_protocol_overview#Construct_a_salmon_magic_envelope)*

Since we don't encrypt the payload anymore, maybe we don't need the double wrapping then? How about making a singe base64url encode over the plain payload?

**Comment by cmrd-senya** [comment]
I've introduced [changes](https://wiki.diasporafoundation.org/index.php?title=Federation_protocol_overview&diff=4719&oldid=4715) to the [overview document](https://wiki.diasporafoundation.org/Federation_protocol_overview#Sending) according to this issue.

**Comment by denschub** [comment]
Wait, @cmrd-senya. There is no point in maintaining two documentations and there is already a fair bit of in-code documentation in this gem, which will be used to generate a federation documentation after the work is done. Manually changing a wiki page is wasted effort. I added a warning to the wiki page.

**Comment by SuperTux88** [comment]
@cmrd-senya: we don't use double base64-encoding for simple magic-envelopes (see [here](https://github.com/SuperTux88/diaspora_federation/blob/76a4ea929b7423d17f6e75e9ddeecfb3b8768d76/lib/diaspora_federation/salmon/magic_envelope.rb#L60)), only for EncryptedSlap, but this will be removed later.

**Comment by redmatrix** [comment]
I've got a question about the JSON (private) side of this. From my reading of this issue and also the updated wiki doco it appears at first glance that there is no way to retrieve the author on the receiving side. Kind of a catch 22. The author is embedded in the encrypted packet and you need to extract the author from the encrypted packet to obtain the correct key to extract the author from the encrypted packet. What am I missing here?
