### ISSUE TITLE
XML deserialization for boolean properties is broken

### ISSUE THREAD

**Issue by cmrd-senya** [diaspora/diaspora_federation#45]
There is a regression from dd1c16ce91958fea743854d2b3b1cb693ae49f0b, which results in broken XML deserialization for the boolean property fields. When you deserialize a `false` value, we still get the default value in the result object.

Here you can find a failing test case: 583359db0851acff6d4f620bf5cbf13b1f94308c

**Comment by SuperTux88** [comment]
Thanks, nice catch!
