### ISSUE TITLE
Remove "parent_author_signature" from relayables

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora_federation#64]
@jaywink asked a few weeks ago, why he needs to add 3 signatures when he sends a comment to his own post (`author_signature`, `parent_author_signature` and the signature in the Magic Envelope, all with the same key). So we can simplify how signatures for relayables are handled:

We can remove `parent_author_signature` completely and use the signature from the Magic Envelope instead, since we receive a relayable always via the parent author (except when we are the parent author). So instead of verifying the `parent_author_signature` we need to verify that the sender of the MagicEnv is the parent author.

There is a little edge case, when the author and the parent author is on the same pod (but not the same person), who sends the MagicEnv then? But I checked the diaspora implementation and also asked @annando for friendica, we already use the parent author in this case, so everything is fine.

There is a special case, when the author is also the parent author. In this case we don't even need to check the `author_signature`, the signature in the Magic Envelope is enough for that.

### v0.2.0 (for diaspora 0.7.0.0)
- [x] don't verify `parent_author_signature` anymore
- [x] verify that the sender of the Magic Envelope is the parent author or the parent is local and we receive the entity from the author directly.
- [x] don't verify `author_signature` if the author is also the parent author
### v0.3.0 (probably for diaspora 0.8.0.0)
- [ ] don't send `parent_author_signature` anymore
- [ ] don't send `author_signature` if the author is also the parent author

**Comment by annando** [comment]
Friendica currently checks the ```parent_author_signature``` and will reject a comment or like when it is missing.

So it seems that for the upcoming 3.5.2 we already should remove the check.

**Comment by SuperTux88** [comment]
Diaspora keeps sending the `parent_author_signature`, so no need to hurry :) 0.7.0.0 well stop checking the signature, and some future unplanned release (maybe 0.8.0.0) then stops sending the `parent_author_signature`, because current diaspora installation would also reject a comment or like when it is missing.

**Comment by jaywink** [comment]
Thanks for taking note of the comment, this is a good improvement imho to simplify implementation 👍
