### ISSUE TITLE
clarification: how are reshare notifications propagated in diaspora? 

### ISSUE THREAD

**Issue by zotlabs** [diaspora/diaspora_federation#96]
It isn't obvious from the Diaspora federation specification how the reshare counter of a post is incremented - what is the notification mechanism by which the original author is made aware of a downstream share? Is it strictly his/her receipt of the reshare message? (If so), how would this work if the reshare is within a limited distribution (or is this prevented?), or is there some other notification mechanism entirely? 

This isn't necessarily a bug but only submitted as an issue in case it might require additional documentation. 

I'm aware there are pending changes in the Diaspora reshare mechanism as a whole. I'm trying my best to reconcile the way this is implemented in red so as to provide basic share compatibility with Diaspora, Zot, OStatus, ActivityPub, DFRN, IndieWeb, (and Twitter).  This may not be possible in every case, but  understanding the details of the Diaspora notification mechanism a bit more may help us to define an alternate base implementation which is slightly more portable across protocol boundaries. Our current implementation does not provide any possibility of share tracking.

**Comment by SuperTux88** [comment]
> Is it strictly his/her receipt of the reshare message?

Yes

> how would this work if the reshare is within a limited distribution

Reshares are only public, and you can only reshare public posts.

> I'm aware there are pending changes in the Diaspora reshare mechanism as a whole.

Yes, it's planned to change how reshares work, so reshares (as we know them now with this reshare message) won't create their own post with own comments anymore, they only increase the visibility of the original post (but comments and likes go to the original post). The [diaspora:// URIs](https://diaspora.github.io/diaspora_federation/federation/diaspora_scheme.html) are planned to be used instead, when you want your own thread, so you can reference a post from another post. Maybe there will be a "reference counter" but this will also only work for references from public posts where the original author receives the post with the `diaspora://` reference.

> Our current implementation does not provide any possibility of share tracking.

When you reshare a public post, just make sure that the original author receives the reshare message.
