### ISSUE TITLE
Requiring a salmon endpoint in webfinger 

### ISSUE THREAD

**Issue by zotlabs** [diaspora/diaspora_federation#98]
Some months ago Diaspora started requiring a 'salmon' endpoint in webfinger or discovery would fail from that service. 

This is problematic for some of my projects because the Diaspora endpoint is not completely salmon compliant and we have a different endpoint for compliant salmon based services; and these services are all optional.  This can lead to somebody trying to connect to Hubzilla (and other servers, including Diaspora) via OStatus and not actually be able to use the salmon endpoint which is advertised.  Yet we have to provide an endpoint or Diaspora discovery will fail. 

Most of our members will enable both Diaspora and OStatus communications, but some are selective and only activate Diaspora - so this causes a problem because the server *appears* to be OStatus compliant yet that service has not been enabled. 

The question is if there is a good reason to make this endpoint **mandatory** in Diaspora, since Diaspora doesn't really use or fully support traditional salmon with xml activitystreams (at least not today). If the reason is to provide discovery of the '/receive' endpoint for Diaspora communications, should not this link have a 'rel' value which is specific to Diaspora and not a 'rel' which incorrectly indicates compliance of a different protocol suite?

Thanks.

**Comment by SuperTux88** [comment]
That was a bug (but nobody reported it for some months) and was already fixed with #97 and will be released with diaspora 0.7.4.0 (and is already fixed on pods running the `develop` branch). So it is still optional, the only real mandatory elements are listed in [the documentation](https://diaspora.github.io/diaspora_federation/discovery/webfinger.html).

**Comment by zotlabs** [comment]
danke.
